### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by tchalvak** [TongTungGiang/MagEngine#1]
How do you install/run/test it?

**Comment by tongtunggiang** [comment]
```
                                                                                  As I said, the Engine is in the very beginning stage. It is not complete yet and it lacks many many things. So there is no‎ install instruction. 
```

**Comment by tchalvak** [comment]
Oh I can see that.  However, part of the benefit of open source is the potential to get outside contributions, which are very unlikely to happen if you can't document a way to get a running demo (as no-one other than you is likely to know what is required at this stage).

I was interested in running something and seeing what happened, but without basic install instructions or script, that's not feasible, so I (and any others) cannot give feedback.

So this is just an FYI from that perspective.

**Comment by tongtunggiang** [comment]
```
                                                                                  I understand. Can I have your email or skype, for discussing about this? I will express my whole idea with you.
```

**Comment by tchalvak** [comment]
Sure, you can hit me up via the email on my profile (though it's a little late here, so I might not end up responding until tomorrow, etc).
